### ISSUE TITLE
Fuction to check token expired or not, trusted or not

### ISSUE THREAD

**Issue by gudipudipradeep** [odwyersoftware/azure-ad-verify-token#1]
Please some one guide me which function I can use from this lib to validate the Authorization token.
I have
CLIENT_ID
CLIENT_SECRET
AUTHORITY

Like valid or not, expired or not, 

Please guide me which function will help for validation the token.

Using Azure B2C

**Comment by richardARPANET** [comment]
There is an example usage at the bottom of the README https://github.com/odwyersoftware/azure-ad-verify-token
