### ISSUE TITLE
Question regarding validating jwt against multiple issuers

### ISSUE THREAD

**Issue by suzannechang** [odwyersoftware/azure-ad-verify-token#4]
Hi,

We have multiple issuers in our sign in sign up flow  that are secured with jwt. I tried putting the multiple issuers in an array. 
But then i got: 
No connection adapters were found for "[['https://

Could you assist? 

Regards. Suzanne

**Comment by richardARPANET** [comment]
That's not yet supported. Would this mean you would want to call `verify_jwt(issuers=list)` and have it return a list of dicts? rather than dict as it is currently?

**Comment by suzannechang** [comment]
Hi Richard,

Something like this?
 
azure_ad_app_id = 'client_id'
azure_ad_issuer = ['issuerurl','issuerurl','issuerurl']
azure_ad_jwks_uri = ['jwksurl','jwksurl','jwksurl']

payload = verify_jwt(
    token='jwttoken ',
    valid_audiences=[azure_ad_app_id],
    issuer=azure_ad_issuer,
    jwks_uri=azure_ad_jwks_uri,
)
 
print(payload)

**Comment by richardARPANET** [comment]
Could you not just call `verify_jwt()` multiple times in a for loop?

**Comment by suzannechang** [comment]
Will do
